(function() {
	var sentences = ["a la vai menusta?",
"Ahtaajien lakoista",
"Aili penaalissa",
"Akkaa kanaalissa",
"Akkumies pihtaalla",
"Alapäinen tikka",
"Ale kanaalissa",
"Alkupäästä kunnossa",
"Alli keulassa",
"Alli kuherteli",
"Alli kuikamoinen",
"Alli kuristaa",
"Alli kuusi",
"Allin kuhertelut",
"Allin kuppeja",
"Allin kusettaminen",
"Allin nenusta",
"Allu pissalla",
"Allua pinnalle",
"Allun pihtaaja",
"Allun piirteet",
"Alotan sinusta",
"Anaa kynnelle",
"Anan penaali",
"Anista pekalle",
"Ankea kanaalissa",
"Antava rinne",
"Antin penaali",
"Antti hinkkanen",
"Antti hirvi",
"Antti-poika",
"Anttilaa kynnelle",
"Appi heristelee",
"Appi kenneliin",
"Appia kenneliin",
"Appia panneen",
"Apua häpeään",
"Araa munille",
"Aran penaali",
"Arin kanaalissa",
"Arpa kynnessä",
"Arpa tukassa",
"Arpia kynnellä",
"Arska teholla",
"Arska tehtaalla",
"Arska tenulle",
"Arska tenussa",
"Arska terabiassa",
"Arskan televisio",
"Arskan termosta",
"Arskan tervaamia",
"Arvaa kannella",
"Arvaamaton kanaali",
"Arvalla kynää",
"Arvon penaali",
"Asetteli kukkaa",
"Avorintaa",
"Baccara kiskalla",
"Bertta karsee",
"Elli kultaantuu",
"Elli kuritti",
"Elli kuteen ottaa",
"Elli viritti",
"Entinen sylvi",
"Eristetty käsinahka",
"Esko paloranta",
"Etupäässä kutoo",
"Hait naisten tanssissa",
"Hakkaamaan puita",
"Halli kujalla",
"Hallit kulkee",
"Hallit kuluineen",
"Hallituskulut",
"Harvassa kypsiä",
"Hassu tuuraaja",
"Hassujen tukijat",
"Hassun tukijat",
"Hattu polki",
"Hattu vialle",
"Hattu viistossa",
"Hattu vinossa",
"Hattulan virtausjuhlat",
"Hattuvaara",
"Hatussa viivoja",
"Hatussa vikoja",
"Hedelmiä kupissa",
"Heikki levonen",
"Heivata kuppia",
"Hekottava pappi",
"Hekottavat papit",
"Helistellä koppia",
"Hellan kulma",
"Hellan vanki",
"Hellin kuppi",
"Hellin kurkku",
"Hennan kans lappiin",
"Hento kuppi",
"Herakuppi",
"Heristävä appi",
"Herjata koppia",
"Herjata pappia",
"Herkkukuppi",
"Herkuttele opeilla",
"Herpa kylmässä",
"Herpaa kylmään",
"Hervoton appi",
"Hevipoppi",
"Hihat panttina",
"Hihaton tantti",
"Hiihtävä pappi",
"Hikka antilla",
"Hikoile runttauksesta",
"Hilajoen antti",
"Hili venttaa",
"Hillin pakoilua",
"Hillitön kurvi",
"Hillitönt kuppaamista",
"Hillitöntä kuppia",
"Hillitönt kuppikansaa",
"Hillua piessä",
"Hinkata rupiaan",
"Hinkattu ruoho",
"Hinkkasen antti",
"Hinkkiä synttäreille",
"Hintalappu",
"Hissi nuljaa",
"Hoikkaa lumoa",
"Hokkasen kaapo",
"Hotkivat pomot",
"Houkka timo",
"Hovisumoilijat",
"Huiskattua ratsua",
"Hukan kapeneminen",
"Hukkakaato",
"Hullu pierasi",
"Hullu piisi",
"Hullun piilillä",
"Hullun piirteet",
"Hullun pimppaa",
"Hullun pimputtelua",
"Hullun pipanoita",
"Hullun pirautus",
"Hulvattomia vuoria",
"Humppilan piimää",
"Huoleton suora",
"Huolettoman suoran",
"Huonot vierailijat",
"Hupia ruorilla",
"Hupia ruoripukilla",
"Hupia ruorista",
"Hurautti pyörällään",
"Huristelen pyörällään",
"Huristelevat pyörät",
"Huristella pyörällään",
"Hurjat kutsut",
"Hurmaava kimalainen",
"Huttua tutkitaan",
"Huttulan virma",
"Huumeinen vierailu",
"Huuteli pyörältään",
"Huutelivat suoraan",
"Hyllyn päällä pilviä",
"Hyrrä päristen",
"Hämeeseen pissimään",
"Härmäläinen passi",
"Hävettää lintaa",
"Iitin simppaa",
"Irja kulma",
"Istuva anssi",
"Jallua piloillaan",
"Jallun piirakkaa",
"Jallut pinoissaan",
"Joilla oli juna muovia",
"Jollaksen yrttitarha",
"Joralan pertti",
"Jukka hurri",
"Junassa kävi mutina",
"Junat muuttuneet",
"Junttihiiri",
"Juoskaa rupisematta",
"Jussi hämäläinen",
"Jussi tinassa",
"Jussi-nukke",
"Jussia nukuttaa",
"Jussien nuotit",
"Juttuja vihdistä",
"Jutut viistoon",
"Jykää tanssaamaan",
"Jyskän pamahdus",
"Jäniksen petos",
"Jänis pettää",
"Järeä kipsi",
"Järeään kipsiin",
"Järvissä kyitä",
"Jätkä korkannut",
"Kaapo hokkanen",
"Kaarat harvassa",
"Kaatunut pulu",
"Kahvin solutusta",
"Kaisan arvoitus",
"Kajauttaa rokit",
"Kakkua alussa",
"Kaksi rekkaa",
"Kalalokki",
"Kalastaja pekka",
"Kalisee pululle",
"Kallista pulu",
"Kallistunut pulu",
"Kallun pihviä",
"Kalpakikkailijat",
"Kalttaa pulmat",
"Kamala hukka",
"Kamppi pirisee",
"Kana murisee",
"Kanaali aluksi",
"Kanaalin arvoitus",
"Kanaista pulua",
"Kanan kanssa muhinoivat",
"Kanat murista",
"Kanat murjun sisään",
"Kania murjaisten",
"Kanit polulle",
"Kannut pekalle",
"Kanttaajan hillo",
"Kapinan alussa",
"Kappelin pimut",
"Kappelin pinnalle",
"Karin olut",
"Karjalan olut",
"Karkeat sukat",
"Karsia kuluja",
"Kartongin kolistaja",
"Karvamisteli",
"Karvan kyntäjä",
"Karvan mikat",
"Karvaton kynä",
"Kasetti kulluu",
"Kassa oli pikkuinen",
"Kastiketta valuun",
"Katri melua",
"Katsaus rukalle",
"Katun virvoitus",
"Katunpuoleinen vintti",
"Kauhea möly",
"Kauhea pöly",
"Kawa repee",
"Kawan renttaus",
"Kehtaava mappi",
"Kekojen sillit",
"Keksitty ralli",
"Kelkkasilli",
"Kelmi perillä",
"Kenopappi",
"Kermaa jonossa",
"Vierumäen juttuja",
"Kessua tupakoidessa",
"Kessua tutuille",
"Kesän malli",
"Kettu vinossa",
"Kettu vitkuttamassa",
"Kettujen vintillä",
"Kettulan vilpoisilla",
"Kettusten vintillä",
"Ketuille vippiä",
"Ketun juosta",
"Kevätrallissa",
"Kieli suhisee",
"Kielipuolet mikkelist",
"Kiitos silli",
"Kiitää huumassa",
"Kilipukki",
"Kiliseväuumainen",
"Kilkuttavaa musaa",
"Kilokorppuja",
"Kinkkuruukku",
"Kipakoita nakkeja",
"Kipeitä ukkoja",
"Kipeä akkeli",
"Kipeä ukkeli",
"Kipureiän ruksautus",
"Kireä ukkeli",
"Kiskomaton ukkeli",
"Kiskovan moksautaja",
"Kitaran hakkeli",
"Kiva kokkeli",
"Kivitetty lokkia",
"Kokkakartonki",
"Koko rahalla",
"Kolkutellut&murissut",
"Kolkutti ja murisi",
"Kolli kuumassa",
"Kolli mourusi",
"Kolli parahtaa",
"Kollikupla",
"Kolossi kartongista",
"Kompin pilaaja",
"Kompin pilkkaaja",
"Komppi pirisee",
"Kopin herjaaja",
"Koplasi heviä",
"Koskelopari",
"Kossu tulee",
"Kossu tuvassa",
"Kossua tukilta",
"Kovaa rallia",
"Kudonnan malli",
"Kudottu silli",
"Kuha ala lilli",
"Kuhaa vallissa",
"Kuhalla rallia",
"Kuhapilli",
"Kuhertaa töllillä",
"Kuhertava alli",
"Kuhertava nalli",
"Kuhmon pelleille",
"Kuhnaava mölli",
"Kuihtunut valli",
"Kuikamoisen allin",
"Kuikutteli olli",
"Kuiskaaja rajala",
"Kuiskaaja rajalla",
"Kuiskaaja rasilainen",
"Kuiskaava ralli",
"Kuiskauksia mollissa",
"Kuiva lasi",
"Kuiva nalli",
"Kuiva napsutus",
"Kuivaa ja nasevaa",
"Kuivaa natinaa",
"Kuivaa soppaa",
"Kuivata vallia",
"Kuivattu velli",
"Kujasen olli",
"Kuka tuli välliin",
"Kukan asetus",
"Kukan millit",
"Kukassa millejä",
"Kukka talli",
"Kukka-polli",
"Kukkaa tukille",
"Kukkaan suksijat",
"Kukkakaalia",
"Kukkanen kallis",
"Kukkiva tölli",
"Kukko rallista",
"Kukkupilli",
"Kukoista mallia",
"Kulaus tilliä",
"Kulhon velliä",
"Kulhovelliä",
"Kullbergin talli",
"Kullervo pelli",
"Kullervo pellinen",
"Kulmassa silli",
"Kulmatalli",
"Kultainen mulli",
"Kultasen silli",
"Kulunut valli",
"Kuluttaa hallia",
"Kumahtanutta silli",
"Kumarassa saksijat",
"Kumea kolli",
"Kumea pilli",
"Kumia salliin",
"Kuminalli",
"Kumistella ollia",
"Kumit ja nasta",
"Kumma jos",
"Kumma valli",
"Kummisedän pullia",
"Kundille mallia",
"Kunnan rasia",
"Kunnan sovitteluelin",
"Kunnanhallitus",
"Kunnassa vallit",
"Kunnollinen tulli",
"Kunnollinen tullimies",
"Kuoro-killinen",
"Kuparipilli",
"Kuparipäisiä nalleja",
"Kupattu ralli",
"Kupillinen heraa",
"Kupittaa sellillä",
"Kupparin ralli",
"Kuppatilliä",
"Kuppi heiluun",
"Kupua hällekin",
"Kuramainen velli",
"Kurasta pallia",
"Kurikan mallit",
"Kurinaa tullissa",
"Kuriseva tilli",
"Kuristettu kolli",
"Kurittaa partisaania",
"Kurittajan pallit",
"Kurja allia",
"Kurja malli",
"Kurja tallilla",
"Kurjan mällin",
"Kurkiallia",
"Kurkistaa tallia",
"Kurkistettu talli",
"Kurkittu palli",
"Kurkku ojalta",
"Kurotettu valli",
"Kurotettua velliä",
"Kurvittomat vallit",
"Kusti polkee",
"Kuten silliä",
"Kutina palleissa",
"Kutinaa tullissa",
"Kutkan pillistä",
"Kutkuttaa lasta",
"Kutova elli",
"Kutsuilla huumetta",
"Kutterin sellissä",
"Kutyyri-salli",
"Kuudes villi",
"Kuukerin nelli",
"Kuultavat killissä",
"Kuuma kolli",
"Kuuma lilli",
"Kuuma pilli",
"Kuuma silli",
"Kuuma tulli",
"Kuuma villi",
"Kuumaa pilliin",
"Kuumassa saksijat",
"Kuumat killissä",
"Kuumat nallissa",
"Kuumiehen malli",
"Kuunteleva silli",
"Kuunteli vällii",
"Kuupullia",
"Kuurapartaiset hallit",
"Kuusi villiä",
"Kuutospullia",
"Kuutossilli",
"Kuvailla tilliä",
"Kuvan rallista",
"Kuvata allia",
"Kuvetta kollissa",
"Kuvuntäytettä hällekin",
"Kyetä tirvalle",
"Kyhnytti turpaa",
"Kylli harvakseltaan",
"Kylli särpimässä",
"Kyllin särvintä",
"Kylmentää varpaansa",
"Kymppi per turpa",
"Kyniä korvista",
"Kynnessä arpia",
"Kynnetty arpa",
"Kynsi turvallaan",
"Kynttiläarpa",
"Kysy arvaten",
"Kytkivät turvat",
"Kytyn vilma",
"Kyyditteli turpaa",
"Kyytiä närpiöön",
"Kämppille piristymään",
"Käsikuhertaja",
"Lallin kumautus",
"Lantin hiivaa",
"Lantit himaan",
"Lasikukko",
"Lasta kurittaa",
"Lasten kuivaajat",
"Latunviiri",
"Leevilla parpattaa",
"Lehtorille viinaa",
"Lelli kuvallaan",
"Lelliä kuvallaan",
"Lennokas inssi",
"Leppä kumahti",
"Lettunen vihoittelee",
"Letunperän vihtori",
"Levynhävittäjä",
"Liialla rahalla",
"Liikaa rahaa",
"Liina pihassa",
"Liina tiukassa",
"Liiskattu pihalle",
"Liitinsuma",
"Likaa mikoille",
"Likan katku",
"Likan kavahdus",
"Liki kohalla",
"Liki pihalle",
"Likka juhasta",
"Lilli kupsahti",
"Lillille kuhaa",
"Lillutella pihasta",
"Limpusta peritään",
"Linjat tahoillaan",
"Linta häkänen",
"Lipeäraha",
"Lipsua rahalle",
"Lirisevä piha",
"Lissu makaa",
"Lissu tupsahtaa",
"Lissu turisee",
"Lissu tutisee",
"Lissua tukasta",
"Liuennut raha",
"Liuotettu takka",
"Lohipiirasta",
"Lohkaistut pullot",
"Lohta kalloo",
"Lokit kirauttivat",
"Lokki kivellä",
"Lommoiset sellot",
"Lompsa pirisee",
"Loppu hyvitettiin",
"Loristettuna pulloista",
"Loskaa pakkiin",
"Loskapaukku",
"Luderastin petkutus",
"Lukeva tutka",
"Lumperin santtu",
"Lumput teostolla",
"Lupsutteli sätkää",
"Lussu tupa",
"Luvan kotkalle",
"Lärvän kytinä",
"Lättyviikari",
"Mahtuneet jollaan",
"Maijan pihalle",
"Malli kuittaa",
"Mallikukkaroita",
"Mallikurssi",
"Mallu pihtailee",
"Mallu pitää pintansa",
"Mallun pidot",
"Mallun pihassa",
"Mallun pikkuinen",
"Mallun pitsi",
"Mankun rullia",
"Manta soittaa",
"Manta sokea",
"Mantaa lakittamassa",
"Mantaako lellit",
"Marikan nassut",
"Matka luiskahti",
"Matkamuisto",
"Maukasta lihaa",
"Mennä pakkoon",
"Mikaa linnassa",
"Mikin kanisterit",
"Mikkelin kittaaja",
"Milliä kukalle",
"Minniä akalle",
"Minttiä hikalle",
"Muhkea tolkutus",
"Muija nalkuttaa",
"Muistelemaan hania",
"Muka vilkussa",
"Mukitolkulla",
"Mulli hana",
"Mulli padassa",
"Mullilla salkku",
"Mullin paistia",
"Multaisa vana",
"Mummi tohkeissaan",
"Mummilla tolkku",
"Mummon salkku",
"Munia kaniin",
"Munkille kalkutusta",
"Muovattu juna",
"Murahtel kolkutukse",
"Murheellinen vilkku",
"Murhia telkussa",
"Murikan mallit",
"Muriseva kolkutus",
"Muriseva pilkku",
"Murjaisi kanille",
"Murjun kana",
"Musa kilkuttaa",
"Musan päälle giniä",
"Musertaa tulkkua",
"Musta kulkku",
"Musta kurisee",
"Mustaa kania",
"Mustanaamio",
"Mustetta nenässä",
"Mustunut kana",
"Mutun vilkku",
"Mutustella viiliä",
"Muutetut sanat",
"Muuttuneet junat",
"Myikö pekka lippua",
"Mylly pörisee",
"Mäntääkö lellit",
"Naama kurtussa",
"Nahjuksen opit",
"Naiselle torttua",
"Naksuttava puimakone",
"Nalleja kuumassa",
"Nalli kurikassa",
"Napakoita huivia",
"Napsu tuvan alta",
"Narvassa kystä",
"Naseva kurttu",
"Nauhatorttua",
"Naurettava soimaan",
"Nenänpää musteessa",
"Niskaa pakottaa",
"Nuhainen vissii",
"Nuhassa ei pissitä",
"Nuoran huljutus",
"Nuorat hukkui",
"Nuppola pissimässä",
"Nurja kassi",
"Nurkasta kiljua",
"Nurkuen passia",
"Nurskuvaa öljyä",
"Nuuka pissimässä",
"Näpelöidä pinniä",
"Närvän kylässä",
"Ohtava markku",
"Oiva kurkku",
"Ojasen kurkut",
"Ojasen serkut",
"Olli kuikkuilee",
"Olli kuikuttelee",
"Olli kujanen",
"Olli kujassa",
"Olli kurjuudessa",
"Olli kurpona",
"Olli kuuntelee",
"Olli painuu",
"Olli pajassa",
"Olli penala",
"Ollille kurkkuja",
"Ollin kumistajat",
"Ollin kuppivuodet",
"Ollin kurjuus",
"Ollin kurkut",
"Ollin paja",
"Ollin serkut",
"Ollista kulkija",
"Ollut herkuttelemassa",
"Olut katettuna",
"Omppua ja banaania",
"Ono parkus",
"Oppia hellille",
"Oppia hevistä",
"Oppistä kassiin",
"Orjakurkku",
"Orkka herkutteli",
"Paahtovalli",
"Paatin täydeltä tuskaa",
"Paatissa tuskaista",
"Paatossilli",
"Padasta mullia",
"Padottu silli",
"Pahaiset viskojat",
"Pahastuneet viskojat",
"Paiskasi raulia",
"Paiskata roskat",
"Paistellessa uneksi",
"Pakahtua tuskaan",
"Pakan millit",
"Pakillinen loskaa",
"Pakkanen katja",
"Pakkelia kittilässä",
"Pakkomeno",
"Pakollinen meno",
"Pakollinen rimputus",
"Pakollinen uneksija",
"Paljas niska",
"Paljas uneksija",
"Palkat niskassa",
"Palkkasilli",
"Palli kumahti",
"Pallia kekoon",
"Pallilla kuiskaten",
"Pallit kukilla",
"Pallit kuriin",
"Pallit vinossa",
"Pallo puskassa",
"Palomies mononen",
"Palon kiskojat",
"Palvottua silliä",
"Pamputettua silliä",
"Panisiko menemään",
"Pankkien roskalainat",
"Pankkien roskat",
"Panttihippa",
"Pappa tiskaa",
"Pappi hekotteli",
"Pappi tuskassa",
"Paraskin sonetti",
"Pari toscaa",
"Parta vellissä",
"Parvella toscaa",
"Pasi kuikka",
"Pasi toikka",
"Paskaa villeille",
"Passin nuppia",
"Passit ja tiketit",
"Passit kuin tiketti",
"Patelan veska",
"Patun viinat",
"Patun vinkki",
"Patut vihottelee",
"Patut viritteli",
"Pavosen heska",
"Pehmeä anis",
"Pehmeä jänis",
"Pehmeä tali",
"Peiliä rappuun",
"Pekan kanteleet",
"Pekan lintu",
"Pekan ministä",
"Pekat kaukalossa",
"Pekka hirsjärvi",
"Pekka hirsmäki",
"Pekka karvonen",
"Pekka lippua",
"Pekka saa linnun",
"Pekko kurvinen",
"Pelattu kolilla",
"Pelin erässä",
"Pelkkää vappua",
"Pellervo hirsjärvi",
"Pellin anis",
"Pellit kerääntyivät",
"Pellit kurseeseen",
"Pellit kurttuun",
"Pelolle vappua",
"Penaali-antti",
"Penaaliarsenaali",
"Penaalin asu",
"Pennillä anista",
"Pennin anis",
"Pennuille jaffaa",
"Pentin lappu",
"Pentti hilkuri",
"Pentti hirsjärvi",
"Pentti hirvonen",
"Pentti karsee",
"Penttilän anis",
"Pepi karsee",
"Pepsiä kirvoille",
"Pernoo-polkka",
"Pertun anista",
"Peruutti lipulla",
"Petattu sohva",
"Pete karsee",
"Petetty jänis",
"Petri karsee",
"Petusta ei vitsiä irtoa",
"Piano-hullu",
"Pianot kulluu",
"Pidellen mallua",
"Pidetty vellu",
"Pieni setti",
"Pietari suuri",
"Piha liukas",
"Piha oli liukas",
"Pihallaan tallustellessa",
"Piharamppi",
"Pihdata jallua",
"Pihdata vallua",
"Pihisevä sumppi",
"Pihisevä tumppi",
"Pihkaista jallua",
"Pihtaava vellu",
"Pihtaileva mallu",
"Pihviä kallulle",
"Pihviä kappelista",
"Piian mallu",
"Piima kuppeli",
"Piira hallussa",
"Piirisumppi",
"Piirteikäs hullu",
"Piiska hallussa",
"Pika-simpukka",
"Pikainen limppu",
"Pikainen limpsa",
"Pikaisesti vieremään",
"Pikapuoli tallusteleen",
"Pikatallustaja",
"Pikavisiitti vieremään",
"Pikkainen kahvi",
"Pikkainen kappeli",
"Pikkainen rilluttelu",
"Pikkainen sapeli",
"Pikkaraisen hallussa",
"Pikkasen hullu",
"Pikkis tullut",
"Pikku-timppa",
"Pikkuinen tallukka",
"Pilallinen jallu",
"Pilata hallussaan",
"Pilata komppi",
"Pilattu timppa",
"Pilkit killuu",
"Pilkullinen muratti",
"Pilli kuonon alla",
"Pilli kuristaa",
"Pillistä kuumat",
"Pillit kumeissa",
"Pillit kuumassa",
"Pilsua hyllystä",
"Pilvi kompissa",
"Pimee komppi",
"Pimeä koli",
"Pimeää kieriskelyä",
"Pimputellaan helluille",
"Pimu-illu",
"Pinkkasivat ruplia käsissään",
"Pinosta melluu",
"Pinta mallussa",
"Pipetti ollut",
"Pippurihylly",
"Pirahtaneet hullut",
"Pirauttaa kassalle",
"Pirisevä hullu",
"Pirisevä omppu",
"Pirisevä tömpsä",
"Piristettä väliin",
"Piristi alia",
"Piristi allia",
"Piristi allua",
"Piristi assia",
"Piristävä assi",
"Piristävä hullu",
"Piristävä limppu",
"Piristävä omppu",
"Piristävä sipuli",
"Piristävä sumppi",
"Piristää pumppua",
"Pirjon mallu",
"Pirkka mallulta",
"Pirkon mallu",
"Pirullinen sumppi",
"Pissiessä nuorittaa",
"Pissitty nunna",
"Pissitty nuuka",
"Pistä kassiin",
"Pitelemään mallua",
"Pitkiä humppia",
"Pitkä kimppu",
"Pitkä tussi",
"Poimuajo",
"Poppi-heikki",
"Potun viskiä",
"Potut villelle",
"Puhdasta aatetta",
"Puimakoneen nahina",
"Puimakone naksutus",
"Puimanakit",
"Pukin kontista",
"Pulinaa kotkassa",
"Pullia paistellessa",
"Pullien kukinto",
"Pulu jokelsi",
"Pulu kaatui",
"Pulu kakilla",
"Pulu kallistui",
"Pulu katosi",
"Pulua kakittaa",
"Puluja kaltatessa",
"Pululla kannukset",
"Pulun katsaus",
"Puntin hillo",
"Puntin hinnalla",
"Punttihillo",
"Puskapassi",
"Pussitilli",
"Pussitteli nuudeleita",
"Pysy tallessa",
"Pyöriä hyllyjen välis",
"Pyöräilevä hullu",
"Pyörällä hulluileen",
"Pyörät huusivat",
"Pässi laihtuneena",
"Pässin silliä",
"Pässiä hätistämässä",
"Pässiä nutistamassa",
"Raha liikkui",
"Rahaa likoon",
"Rahaa listalla",
"Rahamassi",
"Ralli kujalla",
"Ralli kukkuloilla",
"Ralli tukossa",
"Rallia kujalle",
"Rallimies kujala",
"Rannalle jääneet sotamiehet",
"Rapsu tukossa",
"Rapun penkoja",
"Rassukat tuvassa",
"Ratsua huiskaten",
"Raukka pihalla",
"Regina vavahti",
"Reginan vanki",
"Rekkarit ravassa",
"Rellun piinaajat",
"Rellun pippana",
"Ressua tukeen",
"Retun vihkiäiset",
"Retun viuhka",
"Rillit kuvissa",
"Rohkeita muikkuja",
"Rokkikasvot",
"Rukalle tankkaamaan",
"Rukan tankkaajat",
"Rukki kivelle",
"Rukoileva hinkkaaja",
"Ruksautettu kinkku",
"Ruksautti kipureiän",
"Rullit kuiskii",
"Ruma hinkkanen",
"Runon paiskaajat",
"Rusaselle tankkaan",
"Ruskaa pakkasella",
"Ruskan pakoilu",
"Ruskan palautus",
"Ruskan patinaa",
"Ruskapaletti",
"Ruskee konkku",
"Rusoposkinen inkkari",
"Rutosti hinkkaamista",
"Ruttuista viinaa",
"Ruunanen vinkkasi",
"Ruusus-jenkkaa",
"Ryssiä hätyytellä",
"Ryttylän visa",
"Saha lirissä",
"Sahattua linnaa",
"Saksi selvää etua",
"Saksia kumarassa",
"Saksittu kuha",
"Saksittu kuri",
"Salattu piina",
"Salkkua mullille",
"Salkku mutiainen",
"Sallassa kutiainen",
"Salli asetteli kukkaa",
"Salli kuriin",
"Sallin kukat",
"Sallin kutimet",
"Sallin kutu",
"Sallittu kumi",
"Samin runko",
"Samoilija holovaara",
"Sananmuunnos",
"Sankkaa rumbaa",
"Sano pakkanen",
"Sappia kemiin",
"Sarpanevan kyhäelmä",
"Sarpanevan kyhäys",
"Sarvista kyhätty",
"Satsaa ruutanaa",
"Satsattua ruutanaa",
"Selitti vakavasti",
"Sellosta fagotti",
"Sellun pigmentit",
"Sellun pilaaja",
"Selluun pillereitä",
"Sentin pienten",
"Serkku ollissa",
"Sihdattu laari",
"Sihtailee maatin",
"Sihteerin avusta",
"Sikaa liittimestä",
"Sillin kude",
"Sillin kudokset",
"Sillin kurpaleita",
"Sillin kutojat",
"Sillin pantti",
"Silliä a la kultanen",
"Silliä kullekin",
"Silliä kummareissa",
"Silliä kuulin",
"Silliä pankista",
"Simaa liittimestä",
"Sirkka ollila",
"Sirkku ollila",
"Sirpa ja kylli",
"Sirpa kylmillään",
"Sirpa kylmissään",
"Sirpa kylmässä",
"Sirpa kynttilällä",
"Sirpa kypsyttelee",
"Sirpa kytkee",
"Sirpa kytkeytyy",
"Sirpa sai kysyä",
"Sirpa seisoo kylmässä",
"Sirpaa kylliksi",
"Siskojen pamputtajat",
"Sivareita kiitellä",
"Sivuton kiitos",
"Skopin heijaaja",
"Skopin heijari",
"Smart feller",
"Soitto kolahti",
"Sokea manta",
"Sokkelin kivityksessä",
"Solisti hokee",
"Solkkumuusia",
"Solukarja",
"Solutettua kahvia",
"Sorvan kylä",
"Sotamies rannalla",
"Spede burmassa",
"Stress and pitch",
"Suksi kukkaan",
"Suksinko kuuhun",
"Sulloa puoleen",
"Sumokaasu horisee",
"Sumppi pihisee",
"Sumun takia pieleen",
"Suntiota kotiin",
"Suomi lukuelimessä",
"Suora huutelee",
"Suora ja huoleton",
"Sussuille tukijoita",
"Suttu-visanne",
"Syntistä hifiä",
"Syssyn tuoksu",
"Sällit kupsahtivat",
"Taidot nenän takana",
"Takaa linjoille",
"Tallilla kukoomassa",
"Tallista kurinaa",
"Tallukka pikana",
"Taloja kokoomaan",
"Talviin sykkää",
"Tammia mukaan",
"Tankin muna",
"Tankkasi ruhollaan",
"Tapin heittäjät",
"Tarjotaan mukaa",
"Tarun pinkkaus",
"Tehoavaa turskaa",
"Teijalle turskaa",
"Telkku murhistaan",
"Tervalla kypsytetty",
"Tervattu arska",
"Tervon arska",
"Teuvon arska",
"Tiinaa sassiin",
"Tiiraa sassiin",
"Tiketit ja passit",
"Tilannut hissiä",
"Tilit piukassa",
"Tilli kukassa",
"Tillin kukintoja",
"Tillin kukkia",
"Tillin kuskaaminen",
"Timanttiset rossit",
"Timanttista rokkia",
"Timelan passit",
"Timo hokka",
"Timo horisi",
"Timon hoputus",
"Tiputettiin tassille",
"Tirvan kylliäinen",
"Tirvan kyltti",
"Tirvan kylä",
"Tirvan kynäilijä",
"Tirvan kypsyttelyä",
"Tirvan kypät",
"Tissit puhkuen",
"Tolkku muljottaa",
"Tolkkunsa muljottaa",
"Tolkuton mullikka",
"Tolkuttaa muhkeaan",
"Tolujen karilla",
"Tonni käteen",
"Topin herkkua",
"Torvilla kytistä",
"Torvilta kykenee",
"Tosi kurvi",
"Tottua vilppiin",
"Traktorin henssukuosi",
"Truuskraiveri",
"Tuettu kossu",
"Tuhiseva kossu",
"Tuhiseva rassukka",
"Tuima napsu",
"Tuiskattiin rapsut",
"Tukeva kossu",
"Tulista kossua",
"Tulli kuhni",
"Tullimiesten kurinat",
"Tullin kukka",
"Tullin kuppi",
"Tullut pihisee",
"Tullut pihistää",
"Tumma valistuu",
"Tunnin nälissään",
"Tupakoida kessua",
"Turisi houkka",
"Turista kossulla",
"Turista vekkiä",
"Turpa kylessä",
"Turvakaaria",
"Turvallista kossua",
"Turvan kytkijät",
"Turvat kylessä",
"Turvaton kyherö",
"Turvaton kynäilijä",
"Turvato karkulaistyttö",
"Tuskaa paatissa",
"Tuskaa pakottamalla",
"Tuskaista pappia",
"Tuskan parahdus",
"Tuskan patinaa",
"Tuskin kossua",
"Tussi pihisi",
"Tutka lukossa",
"Tutkan lukema",
"Tuttu vihannes",
"Tuttu vihoissa",
"Tuttu vimma",
"Tuttu virassa",
"Tuttu virussa",
"Tuttuja viiletti",
"Tuttuja virtanaan",
"Tutuille viiniä",
"Tutuille vipata",
"Tutuille viskiä",
"Tutun vihellys",
"Tutun virnakkeet",
"Tutun virvokkeita",
"Tutunomaista virvokett",
"Tutusti vinkuu",
"Tutustua viiniin",
"Tutut virposi",
"Tutut virvoittelivat",
"Tutut virvotettua",
"Tuumalle nassua",
"Tuumamitalla nassua",
"Tuumi olli",
"Tuvan alta napsua",
"Tuvanalusnapsuja",
"Tölli kurisee",
"Uimaseuran narut",
"Uiskenteleva nakki",
"Uivat nakit",
"Ukkelit kilisyttää",
"Uneksii paistellessaan",
"Utuista vilinää",
"Vaaralliset kurvit",
"Vaasan lihaa",
"Vaasan linnassa",
"Vaivata reginaa",
"Vakavana selitti",
"Valli kuluu",
"Vallin kuhaa",
"Vallit kuralla",
"Vallu pihalla",
"Vallua ei pilkata",
"Valukastike",
"Vampit pileisiin",
"Vantaan solisti",
"Vappu peltonen",
"Vappulan regina",
"Vattua ja viikunaa",
"Vattuja virtailta",
"Veisas alttona",
"Vektorin hemputus",
"Veli pirinen",
"Vellikulho",
"Vellun pidot",
"Vellun pitopalvelu",
"Veri sataa",
"Verojen hoivaaminen",
"Vesikulho",
"Vieno huttunen",
"Vienoa huttua",
"Vieraileva huttunen",
"Vieras huttu",
"Vierasta pakinaan",
"Vierumäen juttuja",
"Vihainen nuttu",
"Vihainen nuttunsa likaannuttua",
"Vihainen nutussaan",
"Vihannes jorolainen",
"Vihasi vattua",
"Vihdinpuoleis tuttuja",
"Vihdottuja vattuja",
"Vihellys kituuttaa",
"Vihottavaa pottua",
"Vihreänuttuinen",
"Vihtori lettunen",
"Vihtorin lettuja",
"Viikunaa ja vattuja",
"Viileitä pyttyjä",
"Viileä hattu",
"Viili tutuille",
"Viiliä mutustaessa",
"Viima kuha",
"Viimassa kittuuttelua",
"Viimeinen kuttu",
"Viina ja ruttu",
"Viirullinen hattu",
"Viirullisessa hatussaan",
"Viisut katulle",
"Viitossilli",
"Viittasi tuttuun",
"Viiva hatussa",
"Viivoitettu hattu",
"Vikbergin kuttu",
"Viklundin hattu(kaup.)",
"Viljaa kaakille",
"Viljaa kadussa",
"Vilkaista hattua",
"Vilkaista juttua",
"Vilkaista pottua",
"Vilkasta kettua",
"Vilkku muurilla",
"Vilkuta mulle",
"Vilkuta murheellisesti",
"Villahattu",
"Villeille paareja",
"Villen pottuja",
"Villessä tuttua",
"Villi paari",
"Villien kuppaus",
"Villien kuritus",
"Villien tapit piiloon",
"Villin kuhaa",
"Villin kulautus",
"Villin kuppaus",
"Villin kuritus",
"Villinpuoleinen juttu",
"Villissä tuttuja",
"Villit kuumana",
"Villivattu",
"Villiä patuille",
"Villiä ruttuun",
"Vilmannin hattukauppa",
"Vilpoisa kettu",
"Vilttihattu",
"Vilu kantilla",
"Vilu kapajaa",
"Vilu keskel kattuu",
"Vilua hattua myöten",
"Viluissaan hatut",
"Vilukaali",
"Vilulettu",
"Vilvoitettu hattu",
"Vimmainen vattu",
"Vinaa hattuun",
"Vinhoja vattuja",
"Vinkade mellan rosor",
"Vinkkari rutussa",
"Vinkkari-ruunanen",
"Vinkki tutuille",
"Vippaa tutuille",
"Vippiä ketuille",
"Viralliset kutut",
"Virallisia pottuja",
"Viraston vatut",
"Viraton pottu",
"Viraton vattu",
"Virinnyt kettu",
"Viritteli hattua",
"Virittäjä paananen",
"Virkistetty tuttu",
"Virkisti tipua",
"Virkkalan pottuja",
"Virmahuttu",
"Virmehuttu",
"Viron hatut",
"Viron pottu",
"Viron tutut",
"Virpiä kylliksi",
"Virtain Hattu",
"Virtain vattuja",
"Virtakäyttöinen kettu",
"Virtaselle vattun",
"Virtasen patun",
"Virtsa juttu",
"Virvotetut tutut",
"Viskilettu",
"Viskilätty",
"Viskipottu",
"Viskiä lättyyn",
"Viskiä tutuille",
"Vispattu lettu",
"Vissin nuotti",
"Vitkutteleva kettu",
"Viuhahtava lettu",
"Viulisti huttunen",
"Viulut kituuttaa",
"Votkaa jäillä",
"Vällyt pihalle",
"Wirkkalan pottuja",
"Yksi kuha",
"Zulut kajauttaa",
"Älliä ja kukkia",
"Äänisen kypärät"],
	len = sentences.length;	

	var ready = function() {
		var nextSentence = function(e) {
			var rand = Math.floor(Math.random() * len);
			document.getElementById("sentence").innerHTML = sentences[rand] + ".";
			e.preventDefault();
		};
		document.getElementById("next").addEventListener("click", nextSentence, false);
	};

	window.addEventListener('load', ready);

})();
